### ISSUE TITLE
Consider creating separate branches for different channels

### ISSUE THREAD

**Issue by paluh** [cprussin/nixjs#6]
Hi,

as I'm working currently on a PR for purs-0.12.5 I've started to think that it probably be good to provide separate branches for different channels to have really reproducible builds. I mean branches matching exact channels numbering like nixos-18.03, nixos-18.09, nixos-19.03 etc.

What do you think?

**Comment by cprussin** [comment]
Funny, I was just thinking I'd be getting a ticket like this sooner or later :)

I've gone ahead and set up release branches for 18.09 (branched from the last commit that was known to be good on 18.09) and 19.03.  The branch names are `release-18.09` and `release-19.03` (following `home-manager` convention here).  You should be able to use them by referencing nixjs like so:

```nix
{
  purescript ? "0.12.4",
  nixjs ? fetchTarball "https://github.com/cprussin/nixjs/tarball/release-19.03",
  nixpkgs ? <nixpkgs>
}:

let
  nixjs-overlay = import nixjs { inherit purescript; };
  pkgs = import nixpkgs { overlays = [ nixjs-overlay ]; };
in

pkgs.mkShell {
  buildInputs = [ pkgs.purescript ];
}
```

Let me know if you see any issues, thanks!

~~As an aside, I'm fairly sure the purescript package in the `release-19.03` branch is currently broken, but I haven't had a chance to figure it out and fix it.  I was hoping to get to it over the weekend but I didn't end up having time.  If you know better than I what's wrong with it, I would greatly appreciate any help you can provide here.~~ **EDIT**: Looks like I was just using an unsupported GHC version to compile purescript.  I updated that and seems like I've fixed the PS packages now.
